name: pipeline
on: 
  push:
    branches:
    - src # only rebuild site if src branch gets changed

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2.2.0
          with:
            hugo-version: '0.68.3'
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
            publish_branch: master
